#!/bin/bash
./configure --prefix=/usr --target-list=i386-softmmu,x86_64-softmmu,i386-linux-user,x86_64-linux-user --disable-strip --disable-werror --enable-tcg-interpreter --disable-docs --enable-sdl --enable-kvm --disable-attr --enable-libusb --enable-lzo --enable-bzip2 --enable-tools

